# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ssh -i ${{ Secrets.SSH_KEY }} ec2-user@52.64.119.196
      - run: yarn
      - run: yarn build --if-present
      - run: ssh -tt localhost
      - run: ssh -i ec2-user@52.64.119.196
        env:
          CI: true
